//! Signed forwarded client context for gateway-to-backend requests.
//!
//! When a gateway proxies a client request to a backend, it attaches a
//! cryptographically signed context so the backend can verify that the
//! request was forwarded by a trusted gateway and has not been replayed.

use anyhow::{Context, Result};
use base64::{engine::general_purpose, Engine as _};
use lib_crypto::{hash_blake3, KeyPair};
use lib_identity::ZhtpIdentity;
use crate::types::ZhtpRequest;
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};
use tracing::debug;

/// Context attached to proxied requests so backends can verify origin.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ForwardedClientContext {
    /// Gateway DID that signed this context.
    pub gateway_did: String,
    /// Optional original client identifier (e.g. client DID or session token).
    pub original_client_id: Option<String>,
    /// Source IP of the incoming client connection.
    pub source_ip: Option<String>,
    /// Monotonic request id generated by the gateway.
    pub request_id: String,
    /// Unix timestamp in milliseconds when the gateway received the request.
    pub received_at_ms: u64,
    /// TTL in milliseconds; backends should reject stale contexts.
    pub ttl_ms: u64,
}

impl ForwardedClientContext {
    /// Create a new context for the current request.
    pub fn new(
        gateway_did: String,
        original_client_id: Option<String>,
        source_ip: Option<String>,
        ttl_ms: u64,
    ) -> Self {
        let request_id = uuid::Uuid::new_v4().to_string();
        let received_at_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        Self {
            gateway_did,
            original_client_id,
            source_ip,
            request_id,
            received_at_ms,
            ttl_ms,
        }
    }

    /// Returns true if the context has not expired.
    pub fn is_fresh(&self) -> bool {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        now.saturating_sub(self.received_at_ms) <= self.ttl_ms
    }

    /// Canonical byte representation used for signing and verification.
    pub fn canonical_bytes(&self) -> Result<Vec<u8>> {
        serde_json::to_vec(self).context("Failed to serialize ForwardedClientContext")
    }

    /// Compute the blake3 hash of the canonical bytes.
    pub fn hash(&self) -> Result<[u8; 32]> {
        let bytes = self.canonical_bytes()?;
        Ok(hash_blake3(&bytes))
    }
}

/// Sign a context using the gateway's identity keypair.
pub fn sign_context(identity: &ZhtpIdentity, ctx: &ForwardedClientContext) -> Result<Vec<u8>> {
    let private_key = identity
        .private_key
        .as_ref()
        .context("Identity missing private key; cannot sign forwarded context")?;

    let keypair = KeyPair {
        public_key: identity.public_key.clone(),
        private_key: private_key.clone(),
    };

    let hash = ctx.hash()?;
    let signature = keypair
        .sign(&hash)
        .context("Failed to sign forwarded context")?;

    debug!(
        gateway_did = %identity.did,
        request_id = %ctx.request_id,
        "Signed ForwardedClientContext"
    );

    Ok(signature.signature)
}

/// Verify a forwarded context against a known gateway public key.
pub fn verify_context(
    ctx: &ForwardedClientContext,
    signature_bytes: &[u8],
    gateway_public_key: &lib_crypto::PublicKey,
) -> Result<bool> {
    if !ctx.is_fresh() {
        return Ok(false);
    }

    let hash = ctx.hash()?;
    let signature = lib_crypto::Signature::from_bytes_with_key(signature_bytes, gateway_public_key.clone());

    gateway_public_key
        .verify(&hash, &signature)
        .context("Signature verification failed")
}

/// Attach a signed forwarded context to a ZHTP request.
pub fn attach_context(
    mut request: ZhtpRequest,
    ctx: &ForwardedClientContext,
    signature_bytes: &[u8],
) -> Result<ZhtpRequest> {
    let ctx_json = serde_json::to_string(ctx).context("Failed to serialize context")?;
    let ctx_b64 = general_purpose::STANDARD.encode(ctx_json);
    let sig_b64 = general_purpose::STANDARD.encode(signature_bytes);

    request = request.with_custom_header("X-ZHTP-GW-CTX".to_string(), ctx_b64);
    request = request.with_custom_header("X-ZHTP-GW-SIG".to_string(), sig_b64);

    Ok(request)
}

/// Parse raw context and signature bytes from an incoming request without verifying.
/// Returns `Ok(None)` if the gateway headers are absent.
pub fn parse_context(request: &ZhtpRequest) -> Result<Option<(ForwardedClientContext, Vec<u8>)>> {
    let ctx_b64 = match request.headers.custom.get("X-ZHTP-GW-CTX") {
        Some(v) => v,
        None => return Ok(None),
    };
    let sig_b64 = match request.headers.custom.get("X-ZHTP-GW-SIG") {
        Some(v) => v,
        None => return Ok(None),
    };

    let ctx_json = general_purpose::STANDARD
        .decode(ctx_b64)
        .context("Failed to base64-decode forwarded context")?;
    let ctx: ForwardedClientContext =
        serde_json::from_slice(&ctx_json).context("Failed to parse forwarded context")?;

    let sig_bytes = general_purpose::STANDARD
        .decode(sig_b64)
        .context("Failed to base64-decode forwarded context signature")?;

    Ok(Some((ctx, sig_bytes)))
}

/// Extract and verify a forwarded context from an incoming request.
pub fn extract_context(
    request: &ZhtpRequest,
    gateway_public_key: &lib_crypto::PublicKey,
) -> Result<Option<ForwardedClientContext>> {
    let (ctx, sig_bytes) = match parse_context(request)? {
        Some(v) => v,
        None => return Ok(None),
    };

    if !verify_context(&ctx, &sig_bytes, gateway_public_key)? {
        return Err(anyhow::anyhow!(
            "ForwardedClientContext signature verification failed or context is stale"
        ));
    }

    Ok(Some(ctx))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_identity() -> ZhtpIdentity {
        ZhtpIdentity::new_unified(
            lib_identity::IdentityType::Device,
            None,
            None,
            "test-device",
            Some([0u8; 64]),
        )
        .expect("test identity")
    }

    #[test]
    fn sign_and_verify_roundtrip() {
        let identity = test_identity();
        let ctx = ForwardedClientContext::new(
            identity.did.clone(),
            Some("client-123".to_string()),
            Some("192.168.1.1".to_string()),
            60_000,
        );
        let sig = sign_context(&identity, &ctx).expect("sign");
        let valid = verify_context(&ctx, &sig, &identity.public_key).expect("verify");
        assert!(valid);
    }

    #[test]
    fn verify_rejects_stale_context() {
        let identity = test_identity();
        let mut ctx = ForwardedClientContext::new(
            identity.did.clone(),
            None,
            None,
            0,
        );
        // Manually backdate so it is immediately stale
        ctx.received_at_ms = 0;
        let sig = sign_context(&identity, &ctx).expect("sign");
        let valid = verify_context(&ctx, &sig, &identity.public_key).expect("verify");
        assert!(!valid);
    }

    #[test]
    fn attach_and_parse_context() {
        let identity = test_identity();
        let ctx = ForwardedClientContext::new(
            identity.did.clone(),
            Some("client-456".to_string()),
            Some("10.0.0.1".to_string()),
            30_000,
        );
        let sig = sign_context(&identity, &ctx).expect("sign");
        let request = ZhtpRequest::get("/test".to_string(), None).expect("valid request");
        let attached = attach_context(request, &ctx, &sig).expect("attach");

        let (parsed_ctx, parsed_sig) = parse_context(&attached).expect("parse").expect("some");
        assert_eq!(parsed_ctx.gateway_did, ctx.gateway_did);
        assert_eq!(parsed_ctx.source_ip, ctx.source_ip);
        assert_eq!(parsed_sig, sig);
    }

    #[test]
    fn parse_returns_none_when_headers_missing() {
        let request = ZhtpRequest::get("/test".to_string(), None).expect("valid request");
        assert!(parse_context(&request).expect("parse").is_none());
    }
}
